### ISSUE TITLE
Feature request: Add default .gitignore file for skytool files.

### ISSUE THREAD

**Issue by asugaya-apx** [APXLabs/skylight-extension-tool#3]

**Comment by asugaya-apx** [comment]
Done

**Comment by asugaya-apx** [comment]
In version 0.0.12

**Comment by johny-johnson** [comment]
@asugaya-apx When I tried latest with `skytool init -f` I got the following:

> PS C:\code\customer-solutions\cs-ge-aviation-mr> skytool init -f
> Error: ENOENT: no such file or directory, copyfile 'C:\Users\johny.johnson\AppData\Roaming\npm\node_modules\skytool\cli\files\.gitignore' -> 'C:\code\customer-solutions\cs-ge-aviation-mr\.gitignore'
>     at Object.copyFileSync (fs.js:1823:3)
>     at Language.init (C:\Users\johny.johnson\AppData\Roaming\npm\node_modules\skytool\cli\language.js:40:12)
>     at Language.init (C:\Users\johny.johnson\AppData\Roaming\npm\node_modules\skytool\cli\languages\cs.js:45:21)
>     at Command.callback (C:\Users\johny.johnson\AppData\Roaming\npm\node_modules\skytool\cli\commands\init.js:54:24)
>     at Object.handler (C:\Users\johny.johnson\AppData\Roaming\npm\node_modules\skytool\cli\main.js:20:23)
>     at Object.runCommand (C:\Users\johny.johnson\AppData\Roaming\npm\node_modules\skytool\node_modules\yargs\lib\command.js:240:40)
>     at Object.parseArgs [as _parseArgs] (C:\Users\johny.johnson\AppData\Roaming\npm\node_modules\skytool\node_modules\yargs\yargs.js:1107:41)
>     at Object.get [as argv] (C:\Users\johny.johnson\AppData\Roaming\npm\node_modules\skytool\node_modules\yargs\yargs.js:1041:21)
>     at Object.<anonymous> (C:\Users\johny.johnson\AppData\Roaming\npm\node_modules\skytool\cli\main.js:26:34)
>     at Module._compile (internal/modules/cjs/loader.js:1151:30) {
>   errno: -4058,
>   syscall: 'copyfile',
>   code: 'ENOENT',
>   path: 'C:\\Users\\johny.johnson\\AppData\\Roaming\\npm\\node_modules\\skytool\\cli\\files\\.gitignore',
>   dest: 'C:\\code\\customer-solutions\\cs-ge-aviation-mr\\.gitignore'
> }
